// <auto-generated />
using LoomEgypt.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoomEgypt.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LoomEgypt.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ShippingFees")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description-1",
                            Name = "Category-1",
                            ShippingFees = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description-2",
                            Name = "Category-2",
                            ShippingFees = 7.80m
                        });
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryID = 1,
                            Description = "Product Description-1",
                            Name = "Product-1"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Canon",
                            CategoryID = 2,
                            Description = "Product Description-2",
                            Name = "Product-2"
                        });
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productID");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "https://picsum.photos/id/1/200/300",
                            productID = 1
                        },
                        new
                        {
                            Id = 2,
                            Path = "https://picsum.photos/id/10/200/300",
                            productID = 1
                        },
                        new
                        {
                            Id = 3,
                            Path = "https://picsum.photos/id/100/200/300",
                            productID = 2
                        },
                        new
                        {
                            Id = 4,
                            Path = "https://picsum.photos/id/1000/200/300",
                            productID = 2
                        });
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.Product", b =>
                {
                    b.HasOne("LoomEgypt.Domain.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("LoomEgypt.Domain.Entities.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LoomEgypt.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
